import { DatabaseSync } from 'node:sqlite';

const SCHEMA_STATEMENTS = [
  `PRAGMA foreign_keys = ON`,
  `CREATE TABLE IF NOT EXISTS sources (
    id uuid PRIMARY KEY,
    code varchar NOT NULL UNIQUE,
    name varchar NOT NULL,
    publisher varchar,
    license_name varchar,
    license_url varchar,
    is_homebrew boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS lookups (
    id uuid PRIMARY KEY,
    source_id uuid NOT NULL REFERENCES sources(id),
    lookup_type varchar NOT NULL,
    code varchar NOT NULL,
    name varchar NOT NULL,
    parent_lookup_id uuid REFERENCES lookups(id),
    sort_order int,
    numeric_value decimal(12,4),
    text_value text,
    json_value jsonb,
    description text,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS entities (
    id uuid PRIMARY KEY,
    source_id uuid NOT NULL REFERENCES sources(id),
    entity_type varchar NOT NULL,
    parent_entity_id uuid REFERENCES entities(id),
    slug varchar UNIQUE,
    code varchar,
    name varchar NOT NULL,
    size_lookup_id uuid REFERENCES lookups(id),
    spellcasting_ability_lookup_id uuid REFERENCES lookups(id),
    hit_die int,
    level_min int,
    level_max int,
    primary_lookup_ids jsonb,
    granted_lookup_ids jsonb,
    movement_json jsonb,
    prerequisite_json jsonb,
    choice_rules_json jsonb,
    stats_json jsonb,
    tags_json jsonb,
    description text,
    srd boolean NOT NULL DEFAULT true,
    is_homebrew boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS features (
    id uuid PRIMARY KEY,
    source_id uuid NOT NULL REFERENCES sources(id),
    feature_type varchar NOT NULL,
    slug varchar UNIQUE,
    code varchar,
    name varchar NOT NULL,
    level_required int,
    activation_lookup_id uuid REFERENCES lookups(id),
    rest_lookup_id uuid REFERENCES lookups(id),
    repeatable boolean NOT NULL DEFAULT false,
    requires_choice boolean NOT NULL DEFAULT false,
    prerequisite_json jsonb,
    choice_options_json jsonb,
    uses_json jsonb,
    effects_json jsonb,
    tags_json jsonb,
    description text NOT NULL,
    short_description text,
    srd boolean NOT NULL DEFAULT true,
    is_homebrew boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS spells (
    id uuid PRIMARY KEY,
    source_id uuid NOT NULL REFERENCES sources(id),
    slug varchar UNIQUE,
    code varchar,
    name varchar NOT NULL,
    level int NOT NULL,
    school_lookup_id uuid NOT NULL REFERENCES lookups(id),
    activation_lookup_id uuid REFERENCES lookups(id),
    casting_time varchar NOT NULL,
    range_text varchar NOT NULL,
    duration_text varchar NOT NULL,
    save_ability_lookup_id uuid REFERENCES lookups(id),
    ritual boolean NOT NULL DEFAULT false,
    concentration boolean NOT NULL DEFAULT false,
    verbal boolean NOT NULL DEFAULT false,
    somatic boolean NOT NULL DEFAULT false,
    material boolean NOT NULL DEFAULT false,
    material_description text,
    attack_type varchar,
    components_json jsonb,
    damage_json jsonb,
    scaling_json jsonb,
    tags_json jsonb,
    description text NOT NULL,
    higher_level_text text,
    srd boolean NOT NULL DEFAULT true,
    is_homebrew boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS items (
    id uuid PRIMARY KEY,
    source_id uuid NOT NULL REFERENCES sources(id),
    slug varchar UNIQUE,
    code varchar,
    name varchar NOT NULL,
    item_type_lookup_id uuid NOT NULL REFERENCES lookups(id),
    equipment_slot_lookup_id uuid REFERENCES lookups(id),
    rarity_lookup_id uuid REFERENCES lookups(id),
    cost_currency_lookup_id uuid REFERENCES lookups(id),
    weight_lb decimal(10,2),
    cost_amount decimal(12,2),
    is_magical boolean NOT NULL DEFAULT false,
    requires_attunement boolean NOT NULL DEFAULT false,
    stackable boolean NOT NULL DEFAULT true,
    consumable boolean NOT NULL DEFAULT false,
    tags_json jsonb,
    properties_json jsonb,
    profile_json jsonb,
    description text,
    srd boolean NOT NULL DEFAULT true,
    is_homebrew boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS actors (
    id uuid PRIMARY KEY,
    source_id uuid NOT NULL REFERENCES sources(id),
    slug varchar UNIQUE,
    code varchar,
    name varchar NOT NULL,
    actor_type varchar NOT NULL,
    parent_actor_id uuid REFERENCES actors(id),
    taxonomy_lookup_id uuid REFERENCES lookups(id),
    size_lookup_id uuid REFERENCES lookups(id),
    alignment_lookup_id uuid REFERENCES lookups(id),
    challenge_rating decimal(6,3),
    proficiency_bonus int,
    armor_class int,
    hit_points int,
    hit_dice varchar,
    initiative_bonus int,
    passive_perception int,
    abilities_json jsonb,
    saves_json jsonb,
    skills_json jsonb,
    movement_json jsonb,
    senses_json jsonb,
    languages_json jsonb,
    immunities_json jsonb,
    resistances_json jsonb,
    vulnerabilities_json jsonb,
    conditions_json jsonb,
    traits_json jsonb,
    actions_json jsonb,
    spellcasting_json jsonb,
    inventory_json jsonb,
    description text,
    srd boolean NOT NULL DEFAULT true,
    is_homebrew boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS links (
    id uuid PRIMARY KEY,
    source_id uuid NOT NULL REFERENCES sources(id),
    link_type varchar NOT NULL,
    left_table varchar NOT NULL,
    left_id uuid NOT NULL,
    right_table varchar NOT NULL,
    right_id uuid NOT NULL,
    relationship_role varchar,
    sort_order int,
    level_required int,
    quantity decimal(12,2),
    metadata_json jsonb,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_lookups_lookup_type_code_unique ON lookups (lookup_type, code)`,
  `CREATE INDEX IF NOT EXISTS idx_lookups_lookup_type_name ON lookups (lookup_type, name)`,
  `CREATE INDEX IF NOT EXISTS idx_lookups_parent_lookup_id ON lookups (parent_lookup_id)`,
  // The provided model uses (entity_type, name) uniqueness, but the SRD data contains
  // legitimate duplicates such as 2014/2024 Acolyte and repeated feature names across classes.
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_entities_source_type_code_unique ON entities (source_id, entity_type, code)`,
  `CREATE INDEX IF NOT EXISTS idx_entities_type_name ON entities (entity_type, name)`,
  `CREATE INDEX IF NOT EXISTS idx_entities_source_id ON entities (source_id)`,
  `CREATE INDEX IF NOT EXISTS idx_entities_parent_entity_id ON entities (parent_entity_id)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_features_source_type_code_unique ON features (source_id, feature_type, code)`,
  `CREATE INDEX IF NOT EXISTS idx_features_type_name ON features (feature_type, name)`,
  `CREATE INDEX IF NOT EXISTS idx_features_source_id ON features (source_id)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_spells_source_code_unique ON spells (source_id, code)`,
  `CREATE INDEX IF NOT EXISTS idx_spells_name ON spells (name)`,
  `CREATE INDEX IF NOT EXISTS idx_spells_level_school_lookup_id ON spells (level, school_lookup_id)`,
  `CREATE INDEX IF NOT EXISTS idx_spells_source_id ON spells (source_id)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_items_source_code_unique ON items (source_id, code)`,
  `CREATE INDEX IF NOT EXISTS idx_items_name ON items (name)`,
  `CREATE INDEX IF NOT EXISTS idx_items_item_type_lookup_id ON items (item_type_lookup_id)`,
  `CREATE INDEX IF NOT EXISTS idx_items_source_id ON items (source_id)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_actors_source_code_unique ON actors (source_id, code)`,
  `CREATE INDEX IF NOT EXISTS idx_actors_name ON actors (name)`,
  `CREATE INDEX IF NOT EXISTS idx_actors_actor_type ON actors (actor_type)`,
  `CREATE INDEX IF NOT EXISTS idx_actors_taxonomy_lookup_id ON actors (taxonomy_lookup_id)`,
  `CREATE INDEX IF NOT EXISTS idx_actors_source_id ON actors (source_id)`,
  `CREATE INDEX IF NOT EXISTS idx_links_link_type_left ON links (link_type, left_table, left_id)`,
  `CREATE INDEX IF NOT EXISTS idx_links_link_type_right ON links (link_type, right_table, right_id)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_links_pair_role_unique ON links (
    left_table,
    left_id,
    right_table,
    right_id,
    relationship_role,
    link_type
  )`,
];

export function createNormalizedSchema(db: DatabaseSync): void {
  for (const statement of SCHEMA_STATEMENTS) {
    db.exec(statement);
  }
}
